# docker-compose.yml

version: '3.8'
services:

  postgres:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_DB=skeleton-db
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./create-db.sql:/docker-entrypoint-initdb.d/create-database.sql
    ports:
      - '5432:5432'

volumes:
  postgres: